apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: tongo
spec:
  parallelism: 1
  completions: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: ghcr.io/madacluster/tongo:master
        name: tongo
        env:
          - name: LANGUI_MENTI_URL
            value: https://mentor.com
        resources: {}
      restartPolicy: Never
status: {}
