apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: tongo
spec:
  parallelism: 1
  completions: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: ghcr.io/madacluster/tongo:master
        name: tongo
        resources: {}
      restartPolicy: Never
status: {}
